car:
  service:
    base-url: http://localhost:8080/api
car-parts:
  service:
    base-url: http://localhost:8081/api
marketplace:
  service:
    base-url: http://localhost:8082/api
parser:
  service:
    base-url: http://localhost:8001/api